upd

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,22 +1,30 @@
 #!/usr/bin/env bash
 
-if [[ -z "$1" ]]
+if [[ -v "$WSL" ]]
 then
-    printf "start: missing argument\n"
-    exit 1
-fi
-path="$(realpath "$1")"
-path="${path//\//\\}"
-if [[ "${path:0:5}" == '\mnt\' ]]
-then
-    path="${path:5}"
-    if [[ "$path" == *'\'* ]]
+    xdg-open "$@"
+else 
+    if [[ -z "$1" ]]
     then
-        path="$(echo "$path" | sed -r 's/\\/:\\/')"
-    else
-        path="$path:"
+        printf "start: missing argument\n"
+        exit 1
     fi
-else
-    path="\\\\wsl$\\Ubuntu$path"
+
+    path="$(realpath "$1")"
+    path="${path//\//\\}"
+
+    if [[ "${path:0:5}" == '\mnt\' ]]
+    then
+        path="${path:5}"
+        if [[ "$path" == *'\'* ]]
+        then
+            path="$(echo "$path" | sed -r 's/\\/:\\/')"
+        else
+            path="$path:"
+        fi
+    else
+        path="\\\\wsl$\\Ubuntu$path"
+    fi
+
+    cmd.exe /C start "$path" 2> /dev/null
 fi
-cmd.exe /C start "$path" 2> /dev/null
