upd

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,15 +1,21 @@
 #!/usr/bin/env sh
 
+if [ "$#" -eq "0" ]
+then
+    printf "start: missing argument\n" >&2
+    exit 1
+fi
+
+if [ ! -e "$1" ]
+then
+    printf "start: file \`%s' does not exist\n" "$1" >&2
+    exit 1
+fi
 
 if [ -z "$WSL" ]
 then
-    xdg-open "$@" 1> /dev/null &
+    xdg-open "$1" 1> /dev/null &
 else 
-    if [ "$#" -eq "0" ]
-    then
-        printf "start: missing argument\n" >&2
-        exit 1
-    fi
 
     if case "$path" in 'http://'*) true;; 'https://'*) true;; *) false;; esac;
     then
